### ISSUE TITLE
occasional crashes

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1239]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2759661]

goroutine 72 [running]:
github.com/docker/compose-cli/local.(*composeService).attachContainerStreams.func1(0x34c7c00, 0xc0005b4540, 0x34aac80, 0xc0005b4740, 0x0, 0x0)
        github.com/docker/compose-cli/local/compose.go:412 +0x61
created by github.com/docker/compose-cli/local.(*composeService).attachContainerStreams
        github.com/docker/compose-cli/local/compose.go:409 +0x12c
˙˙˙
```

reported on https://github.com/docker/compose-cli/issues/1235

**Comment by gtardif** [comment]
Will reopen if happens again
