### ISSUE TITLE
Panic in docker version

### ISSUE THREAD

**Issue by ebriney** [docker/compose-cli#1320]
**Description**

We had a panic in Docker Desktop (mac) when shell outing legacy version. It only happens once but just in case it's an obvious race I put the stack dump there.

**Steps to reproduce the issue:**

It's transient error in our CI. Perhaps doing a similar stress test (10 commands in parallel in a loop).

**Describe the results you received:**

Panic, then exit code 2

**Describe the results you expected:**

Get the version output, exit without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.8
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:28:27 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**
NB: that's a arm64 issue (perhaps it's go compiler or rosetta2 issue)

```
{
  "ID": "HYZQ:C6VJ:LFHJ:HIFB:TF6X:U5HI:YW4L:PJBK:PNH7:KGRY:UP7K:CESX",
  "Containers": 0,
  "ContainersRunning": 0,
  "ContainersPaused": 0,
  "ContainersStopped": 0,
  "Images": 0,
  "Driver": "overlay2",
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "local",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "KernelMemory": true,
  "KernelMemoryTCP": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "PidsLimit": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": true,
  "BridgeNfIp6tables": true,
  "Debug": false,
  "NFd": 41,
  "OomKillDisable": true,
  "NGoroutines": 47,
  "SystemTime": "2021-02-16T06:02:29.576187138Z",
  "LoggingDriver": "json-file",
  "CgroupDriver": "cgroupfs",
  "CgroupVersion": "1",
  "NEventsListener": 3,
  "KernelVersion": "4.19.121-linuxkit",
  "OperatingSystem": "Docker Desktop",
  "OSVersion": "",
  "OSType": "linux",
  "Architecture": "aarch64",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Mirrors": [
          "http://host.docker.internal:5000/"
        ],
        "Secure": true,
        "Official": true
      },
      "host.docker.internal:5000": {
        "Name": "host.docker.internal:5000",
        "Mirrors": [],
        "Secure": false,
        "Official": false
      }
    },
    "Mirrors": [
      "http://host.docker.internal:5000/"
    ]
  },
  "NCPU": 4,
  "MemTotal": 2077294592,
  "GenericResources": null,
  "DockerRootDir": "/var/lib/docker",
  "HttpProxy": "",
  "HttpsProxy": "",
  "NoProxy": "",
  "Name": "docker-desktop",
  "Labels": [],
  "ExperimentalBuild": false,
  "ServerVersion": "20.10.3",
  "Runtimes": {
    "io.containerd.runc.v2": {
      "path": "runc"
    },
    "io.containerd.runtime.v1.linux": {
      "path": "runc"
    },
    "runc": {
      "path": "runc"
    }
  },
  "DefaultRuntime": "runc",
  "Swarm": {
    "NodeID": "",
    "NodeAddr": "",
    "LocalNodeState": "inactive",
    "ControlAvailable": false,
    "Error": "",
    "RemoteManagers": null
  },
  "LiveRestoreEnabled": false,
  "Isolation": "",
  "InitBinary": "docker-init",
  "ContainerdCommit": {
    "ID": "269548fa27e0089a8b8278fc4fc781d7f65a939b",
    "Expected": "269548fa27e0089a8b8278fc4fc781d7f65a939b"
  },
  "RuncCommit": {
    "ID": "ff819c7e9184c13b7c2607fe6c30ae19403a7aff",
    "Expected": "ff819c7e9184c13b7c2607fe6c30ae19403a7aff"
  },
  "InitCommit": {
    "ID": "de40ad0",
    "Expected": "de40ad0"
  },
  "SecurityOptions": [
    "seccomp"
  ],
  "Warnings": null,
  "ExecutionDriver": "<not supported>"
}
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Docker Desktop mac, local

Stack trace:
```
error running [docker version]:
Command stdout:
stderr:
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x1 addr=0x0 pc=0x102fdf0]
goroutine 3 [running]:
runtime.throw(0x32eeb6a, 0x2a)
	runtime/panic.go:1116 +0x72 fp=0xc00006f5c8 sp=0xc00006f598 pc=0x1035b32
runtime.sigpanic()
	runtime/signal_unix.go:726 +0x48c fp=0xc00006f5f8 sp=0xc00006f5c8 pc=0x104b94c
runtime.(*spanSet).push(0x4839818, 0x31a39660)
	runtime/mspanset.go:76 +0x30 fp=0xc00006f658 sp=0xc00006f5f8 pc=0x102fdf0
runtime.(*mspan).sweep(0x31a39660, 0x31a39600, 0x0)
	runtime/mgcsweep.go:530 +0x69e fp=0xc00006f740 sp=0xc00006f658 pc=0x102507e
runtime.sweepone(0x334e1d0)
	runtime/mgcsweep.go:233 +0x28d fp=0xc00006f7a8 sp=0xc00006f740 pc=0x10247ad
runtime.bgsweep(0xc000042070)
	runtime/mgcsweep.go:166 +0xbe fp=0xc00006f7d8 sp=0xc00006f7a8 pc=0x102445e
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc00006f7e0 sp=0xc00006f7d8 pc=0x106b001
created by runtime.gcenable
	runtime/mgc.go:217 +0x5c
goroutine 1 [runnable]:
syscall.Close(0xb, 0xc0000cb688, 0x8)
	syscall/zsyscall_darwin_amd64.go:518 +0xcf
syscall.forkExec(0xc0003ea260, 0x1d, 0xc0005480e0, 0x2, 0x2, 0xc0000cb7a8, 0x47, 0x19af92c600020400, 0xc000433000)
	syscall/exec_unix.go:226 +0x453
syscall.StartProcess(...)
	syscall/exec_unix.go:263
os.startProcess(0xc0003ea260, 0x1d, 0xc0005480e0, 0x2, 0x2, 0xc0000cb940, 0xc000374480, 0x47, 0x47)
	os/exec_posix.go:53 +0x29b
os.StartProcess(0xc0003ea260, 0x1d, 0xc0005480e0, 0x2, 0x2, 0xc0000cb940, 0x47, 0xc000540270, 0x1ed)
	os/exec.go:102 +0x7c
os/exec.(*Cmd).Start(0xc000174160, 0x1, 0xc00053a0f0)
	os/exec/exec.go:422 +0x528
os/exec.(*Cmd).Run(0xc000174160, 0xc00053a0f0, 0xc000174160)
	os/exec/exec.go:338 +0x2b
os/exec.(*Cmd).CombinedOutput(0xc000174160, 0xe, 0xc000380090, 0x1, 0x1, 0xc000174160)
	os/exec/exec.go:567 +0x91
github.com/docker/compose-cli/cli/mobycli.ExecSilent(0x364abe0, 0xc00058e000, 0xc000380090, 0x1, 0x1, 0xc0004f4150, 0x3298322, 0x7, 0xc00046b338, 0x209498d47)
	github.com/docker/compose-cli/cli/mobycli/exec.go:124 +0xcb
github.com/docker/compose-cli/cli/cmd.getOutFromMoby(0xc000487340, 0xc000380090, 0x1, 0x1, 0x1, 0x1)
	github.com/docker/compose-cli/cli/cmd/version.go:73 +0x65
github.com/docker/compose-cli/cli/cmd.runVersion(0xc000487340)
	github.com/docker/compose-cli/cli/cmd/version.go:60 +0x1ad
github.com/docker/compose-cli/cli/cmd.VersionCommand.func1(0xc000487340, 0x4840c58, 0x0, 0x0)
	github.com/docker/compose-cli/cli/cmd/version.go:41 +0x2b
github.com/spf13/cobra.(*Command).execute(0xc000487340, 0x4840c58, 0x0, 0x0, 0xc000487340, 0x4840c58)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000467080, 0xc00053ac60, 0x2d04400, 0x4840c58)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.1/command.go:888
main.main()
	github.com/docker/compose-cli/cli/main.go:202 +0xa37
goroutine 6 [chan send]:
github.com/docker/compose-cli/cli/formatter.init.0.func1(0xc000100b40)
	github.com/docker/compose-cli/cli/formatter/colors.go:77 +0x2f5
created by github.com/docker/compose-cli/cli/formatter.init.0
	github.com/docker/compose-cli/cli/formatter/colors.go:61 +0x22b
goroutine 14 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x480f180)
	k8s.io/klog/v2@v2.4.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.4.0/klog.go:417 +0xdf
goroutine 33 [syscall]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:144 +0x9d
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x45
goroutine 20 [chan receive]:
main.newSigContext.func1(0xc00048c180, 0xc000214540)
	github.com/docker/compose-cli/cli/main.go:267 +0x34
created by main.newSigContext
	github.com/docker/compose-cli/cli/main.go:266 +0x105
error:
exit status 2
```

**Comment by gtardif** [comment]
Will reopen if really happen again
