### ISSUE TITLE
Flaky test fail in TestCascadeStop

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1508]
Seen in CI at https://github.com/docker/compose-cli/pull/1501/checks?check_run_id=2287195493#step:9:80: 

```
✖  local/e2e/compose (1m27.889s)

make: *** [Makefile:48: e2e-local] Error 1
=== Failed
=== FAIL: local/e2e/compose TestCascadeStop/abort-on-container-exit (18.57s)
	[TestCascadeStop] docker compose -f ./fixtures/cascade-stop-test/compose.yaml --project-name e2e-cascade-stop up --abort-on-container-exit
    cascade_stop_test.go:34: assertion failed: 
        Command:  /tmp/669697575/docker compose -f ./fixtures/cascade-stop-test/compose.yaml --project-name e2e-cascade-stop up --abort-on-container-exit
        ExitCode: 2
        Error:    exit status 2
        Stdout:   #1 [should_fail internal] load build definition from Dockerfile
        #1 sha256:45ae60f0aff0adae18f641424ecfee7525b7affd00c5643355a2885551198ae9
        #1 transferring dockerfile: 56B 0.0s done
        #1 DONE 0.0s
        
        #2 [sleep internal] load build definition from Dockerfile
        #2 sha256:0218fcaf2a2af4c1c2048b45a0b873fff7d372ac905a7043578c319cc90451ca
        #2 transferring dockerfile: 56B 0.0s done
        #2 DONE 0.0s
        
        #3 [should_fail internal] load .dockerignore
        #3 sha256:b3ddde648354b0d7aadeaa11a6050bbf72353d13480206670cbbc1731060132f
        #3 transferring context: 2B done
        #3 DONE 0.0s
        
        #4 [sleep internal] load .dockerignore
        #4 sha256:27ce3fd3ea9136503946b756c8f2662d81a8edf4bf355016fab4811d043df13d
        #4 transferring context: 2B done
        #4 DONE 0.0s
        
        #5 [should_fail internal] load metadata for docker.io/library/busybox:1.27.2
        #5 sha256:3033124690457826eccf98b19dcd48488458ad90a0d2959a5db525765549241b
        #5 DONE 0.8s
        
        #6 [should_fail 1/1] FROM docker.io/library/busybox:1.27.2@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0
        #6 sha256:7a149aceb71c72f384e0536ced64bf9369d959f90641a2dff976b34eacd02bf3
        #6 resolve docker.io/library/busybox:1.27.2@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 done
        #6 sha256:0ffadd58f2a61468f527cc4f0fc45272ee4a1a428abe014546c89de2aa6a0eb5 715.30kB / 715.30kB 0.1s done
        #6 sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 2.70kB / 2.70kB done
        #6 sha256:91ef6c1c52b166be02645b8efee30d1ee65362024f7da41c404681561734c465 527B / 527B done
        #6 sha256:6ad733544a6317992a6fac4eb19fe1df577d4dec7529efec28a5bd0edad0fd30 1.50kB / 1.50kB done
        #6 extracting sha256:0ffadd58f2a61468f527cc4f0fc45272ee4a1a428abe014546c89de2aa6a0eb5
        #6 sha256:0ffadd58f2a61468f527cc4f0fc45272ee4a1a428abe014546c89de2aa6a0eb5 715.30kB / 715.30kB 0.1s done
        #6 extracting sha256:0ffadd58f2a61468f527cc4f0fc45272ee4a1a428abe014546c89de2aa6a0eb5 0.1s done
        #6 DONE 0.3s
        
        #7 [should_fail] exporting to image
        #7 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
        #7 exporting layers done
        #7 writing image sha256:a229b61a74acb92240f381a2016654948a162d46f4578aacd3d0e6857e3768fa done
        #7 naming to docker.io/library/busybox:1.27.2 done
        #7 DONE 0.0s
        Attaching to should_fail_1, sleep_1
        sleep_1        | PING localhost (127.0.0.1): 56 data bytes
        sleep_1        | 64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.054 ms
        should_fail_1  | ls: /does_not_exist: No such file or directory
        should_fail_1 exited with code 1
        Aborting on container exit...
        
        Stderr:   Network "e2e-cascade-stop_default"  Creating
        Network "e2e-cascade-stop_default"  Created
        Container e2e-cascade-stop_sleep_1  Creating
        Container e2e-cascade-stop_should_fail_1  Creating
        Container e2e-cascade-stop_should_fail_1  Created
        Container e2e-cascade-stop_sleep_1  Created
        Container e2e-cascade-stop_sleep_1  Stopping
        Container e2e-cascade-stop_should_fail_1  Stopping
        Container e2e-cascade-stop_should_fail_1  Stopped
        Container e2e-cascade-stop_sleep_1  Stopped
        level=error msg=1
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd5a0b9]
        
        goroutine 1 [running]:
        github.com/docker/compose-cli/cli/cmd/compose.runCreateStart(0x2b559e8, 0xc00015d680, 0xc0000ce1e0, 0x0, 0x3d78b50, 0x0, 0x0, 0x1000000000000, 0x0, 0x0, ...)
        	github.com/docker/compose-cli/cli/cmd/compose/up.go:326 +0x739
        github.com/docker/compose-cli/cli/cmd/compose.upCommand.func1(0xc0000e4580, 0xc00051e740, 0x0, 0x1, 0x0, 0x0)
        	github.com/docker/compose-cli/cli/cmd/compose/up.go:171 +0x208
        github.com/spf13/cobra.(*Command).execute(0xc0000e4580, 0xc00003a0f0, 0x1, 0x1, 0xc0000e4580, 0xc00003a0f0)
        	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
        github.com/spf13/cobra.(*Command).ExecuteC(0xc0002e3340, 0xc0005a9e68, 0x3, 0x3)
        	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
        github.com/spf13/cobra.(*Command).Execute(...)
        	github.com/spf13/cobra@v1.1.1/command.go:895
        github.com/spf13/cobra.(*Command).ExecuteContext(...)
        	github.com/spf13/cobra@v1.1.1/command.go:888
        main.main()
        	github.com/docker/compose-cli/cli/main.go:228 +0x94c
        
        
        Failures:
        ExitCode was 2 expected 1
    --- FAIL: TestCascadeStop/abort-on-container-exit (18.57s)

=== FAIL: local/e2e/compose TestCascadeStop/exit-code-from (12.18s)
	[TestCascadeStop] docker compose -f ./fixtures/cascade-stop-test/compose.yaml --project-name e2e-cascade-stop up --exit-code-from=sleep
	[TestStartStop] docker compose ls
	[TestStartStop] docker compose ls --all
	[TestStartStop] docker compose --project-name e2e-start-stop ps
	[TestStartStop] docker compose --project-name e2e-start-stop ps --all
    cascade_stop_test.go:40: assertion failed: 
        Command:  /tmp/669697575/docker compose -f ./fixtures/cascade-stop-test/compose.yaml --project-name e2e-cascade-stop up --exit-code-from=sleep
        ExitCode: 2
        Error:    exit status 2
        Stdout:   Attaching to should_fail_1, sleep_1
        sleep_1        | PING localhost (127.0.0.1): 56 data bytes
        sleep_1        | 64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.060 ms
        should_fail_1  | ls: /does_not_exist: No such file or directory
        should_fail_1 exited with code 1
        Aborting on container exit...
        
        Stderr:   Container e2e-cascade-stop_should_fail_1  Created
        Container e2e-cascade-stop_sleep_1  Created
        Container e2e-cascade-stop_sleep_1  Stopping
        Container e2e-cascade-stop_should_fail_1  Stopping
        Container e2e-cascade-stop_should_fail_1  Stopped
        Container e2e-cascade-stop_sleep_1  Stopped
        level=error msg=137
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd5a0b9]
        
        goroutine 1 [running]:
        github.com/docker/compose-cli/cli/cmd/compose.runCreateStart(0x2b559e8, 0xc0000af640, 0xc000458260, 0x0, 0x3d78b50, 0x0, 0x0, 0x1000000000000, 0x7ffd013010c8, 0x5, ...)
        	github.com/docker/compose-cli/cli/cmd/compose/up.go:326 +0x739
        github.com/docker/compose-cli/cli/cmd/compose.upCommand.func1(0xc0004b22c0, 0xc000389fe0, 0x0, 0x1, 0x0, 0x0)
        	github.com/docker/compose-cli/cli/cmd/compose/up.go:171 +0x208
        github.com/spf13/cobra.(*Command).execute(0xc0004b22c0, 0xc00003a0f0, 0x1, 0x1, 0xc0004b22c0, 0xc00003a0f0)
        	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
        github.com/spf13/cobra.(*Command).ExecuteC(0xc000361340, 0xc00051fe68, 0x3, 0x3)
        	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
        github.com/spf13/cobra.(*Command).Execute(...)
        	github.com/spf13/cobra@v1.1.1/command.go:895
        github.com/spf13/cobra.(*Command).ExecuteContext(...)
        	github.com/spf13/cobra@v1.1.1/command.go:888
        main.main()
        	github.com/docker/compose-cli/cli/main.go:228 +0x94c
        
        
        Failures:
        ExitCode was 2 expected 137
    --- FAIL: TestCascadeStop/exit-code-from (12.18s)

=== FAIL: local/e2e/compose TestCascadeStop (31.40s)
    framework.go:79: Config: 
    framework.go:80: Contents of config dir:
    framework.go:82: /tmp/658153201/tmp/658153201
    framework.go:82: /tmp/658153201/tmp/658153201/contexts
    framework.go:82: /tmp/658153201/tmp/658153201/contexts/meta
```

**Comment by gtardif** [comment]
Actually not a flaky test, related to the PR where it failed
