### ISSUE TITLE
Debugging CLI error with valid compose file 

### ISSUE THREAD

**Issue by steviewanders** [docker/compose-cli#894]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

When calling `docker compose up` in a valid ECS context run into `panic: runtime error: invalid memory address or nil pointer dereference` (full output below)

**Steps to reproduce the issue:**
1. Install all the Docker requirements and local environment like AWS config and ECS context
2. Run `docker compose up` in a directory with a `docker-compose.yaml` file that is valid to `docker-compose`

**Describe the results you received:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21aaf82]

goroutine 39 [running]:
github.com/docker/compose-cli/ecs.(*ecsAPIService).createTaskRole(0xc00004e900, 0xc0006d0cc0, 0xc0000951fa, 0x2, 0x0, 0x0, 0x0, 0x3a40b00, 0x0, 0x0, ...)
        github.com/docker/compose-cli/ecs/cloudformation.go:395 +0x3a2
github.com/docker/compose-cli/ecs.(*ecsAPIService).createService(0xc00004e900, 0xc0006d0cc0, 0xc0000951fa, 0x2, 0x0, 0x0, 0x0, 0x3a40b00, 0x0, 0x0, ...)
        github.com/docker/compose-cli/ecs/cloudformation.go:104 +0x118
github.com/docker/compose-cli/ecs.(*ecsAPIService).convert(0xc00004e900, 0x2d76760, 0xc0006b65a0, 0xc0006d0cc0, 0xc00000e498, 0x2d94ec0, 0xc00000e4b0)
        github.com/docker/compose-cli/ecs/cloudformation.go:83 +0x638
github.com/docker/compose-cli/ecs.(*ecsAPIService).Convert(0xc00004e900, 0x2d76760, 0xc0006b65a0, 0xc0006d0cc0, 0xc, 0x0, 0x0, 0x1, 0x1)
        github.com/docker/compose-cli/ecs/cloudformation.go:41 +0x4d
github.com/docker/compose-cli/ecs.(*ecsAPIService).Up(0xc00004e900, 0x2d76760, 0xc0006b65a0, 0xc0006d0cc0, 0x0, 0x0, 0x0)
        github.com/docker/compose-cli/ecs/up.go:35 +0xc5
github.com/docker/compose-cli/cli/cmd/compose.runUp.func1(0x2d76760, 0xc0006b65a0, 0x0, 0x0, 0x0, 0x0)
        github.com/docker/compose-cli/cli/cmd/compose/up.go:71 +0x11a
github.com/docker/compose-cli/progress.Run.func2(0x0, 0x0)
        github.com/docker/compose-cli/progress/writer.go:102 +0x79
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006b6540, 0xc00004e980)
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

**Describe the results you expected:**

A ECS deployment

**Additional information you deem important (e.g. issue happens only occasionally):**

1. the `docker-compose.yaml` file is here: https://gist.github.com/steviewanders/a21f8c7b03dce9738ecf468440712967

2. I tried Docker Desktop Edge channel and got a different output.

```
at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
status code: 400, request id: b498e514-5d3f-4f78-bfaf-58a563d0c2c2
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "myecscontext",
        "Metadata": {
            "Description": "(ca-central-1)",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Region": "ca-central-1"
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/stevevandervalk/.docker/contexts/meta/8bb20fb47c4248774ab660063891d2332facb5997d914f61b3bdfeb471eaddba",
            "TLSPath": "/Users/stevevandervalk/.docker/contexts/tls/8bb20fb47c4248774ab660063891d2332facb5997d914f61b3bdfeb471eaddba"
        }
    }
]
```

**Output of `docker info`:**

```
Command "info" not available in current context (myecscontext), you can use the "default" context to run this command

(with `default` context)

Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.39-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: CJQY:IUQA:VCJM:XF4I:4A5K:6G5K:Q5H5:DTOF:FNED:AXGE:ZPSJ:EVGA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
root cause: Your compose file uses hosts bind mounts (like `/etc/localtime:/etc/localtime`) which are not supported on ECS with Fargate. 
Obviously ECS integration should report a user-friendly error, not crash like like with `panic`, I'll fix this with a compatibilty check.

**Comment by steviewanders** [comment]
Thank you!

After replacing the binds with volumes and am now seeing 

```
at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
status code: 400, request id: 0da1a8bf-05b7-4e7f-a51c-9c52769c5d1e
```

which was the same error as the Docker for Desktop Edge channel. 
Should I open a separate issue or is this another mistake of mine?

**Comment by ndeloof** [comment]
Right, this is https://github.com/docker/compose-cli/issues/665
