### ISSUE TITLE
Debugging CLI error with valid compose file

### ISSUE THREAD

**Issue by arredgroup** [docker/compose-cli#981]
**Description**

When calling docker compose up in a valid ECS context run into panic: runtime error: invalid memory address or nil pointer dereference (full output below)

**Steps to reproduce the issue:**
Install all the Docker requirements and local environment like AWS config and ECS context
Run docker compose up in a directory with a docker-compose.yaml file that is valid to docker-compose

**Describe the results you received:**
```
WARN[0000] services.build: unsupported attribute        
WARN[0000] services.restart: unsupported attribute      
WARN[0000] services.tty: unsupported attribute          
WARN[0000] services.restart: unsupported attribute      
WARN[0000] services.tty: unsupported attribute          
WARN[0000] services.build: unsupported attribute        
WARN[0000] services.stdin_open: unsupported attribute   
WARN[0000] services.tty: unsupported attribute          
WARN[0000] networks.driver: unsupported attribute       
WARN[0000] volumes.driver: unsupported attribute        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21aaf82]

goroutine 12 [running]:
github.com/docker/compose-cli/ecs.(*ecsAPIService).createTaskRole(0xc00051e640, 0xc000475800, 0xc000095200, 0x3, 0x0, 0x0, 0x0, 0x3a40b00, 0x0, 0x0, ...)
	github.com/docker/compose-cli/ecs/cloudformation.go:395 +0x3a2
github.com/docker/compose-cli/ecs.(*ecsAPIService).createService(0xc00051e640, 0xc000475800, 0xc000095200, 0x3, 0x0, 0x0, 0x0, 0x3a40b00, 0x0, 0x0, ...)
	github.com/docker/compose-cli/ecs/cloudformation.go:104 +0x118
github.com/docker/compose-cli/ecs.(*ecsAPIService).convert(0xc00051e640, 0x2d76760, 0xc000698450, 0xc000475800, 0xc00000e718, 0x2d94ec0, 0xc00000e730)
	github.com/docker/compose-cli/ecs/cloudformation.go:83 +0x638
github.com/docker/compose-cli/ecs.(*ecsAPIService).Convert(0xc00051e640, 0x2d76760, 0xc000698450, 0xc000475800, 0x9, 0x0, 0x0, 0x1, 0x1)
	github.com/docker/compose-cli/ecs/cloudformation.go:41 +0x4d
github.com/docker/compose-cli/ecs.(*ecsAPIService).Up(0xc00051e640, 0x2d76760, 0xc000698450, 0xc000475800, 0x0, 0x0, 0x0)
	github.com/docker/compose-cli/ecs/up.go:35 +0xc5
github.com/docker/compose-cli/cli/cmd/compose.runUp.func1(0x2d76760, 0xc000698450, 0x0, 0x0, 0x0, 0x0)
	github.com/docker/compose-cli/cli/cmd/compose/up.go:71 +0x11a
github.com/docker/compose-cli/progress.Run.func2(0x0, 0x0)
	github.com/docker/compose-cli/progress/writer.go:102 +0x79
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006983f0, 0xc00051e6c0)
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66

```
**Describe the results you expected:**
A ECS deployment

**Additional information you deem important (e.g. issue happens only occasionally):**
the docker-compose.yaml:
```
version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/backend
    volumes:
      # - ./backend/supervisor.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./backend:/var/www/backend
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - x-aws-protocol: http
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  #ReactJS
  react-ui:
    image: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - x-aws-protocol: http
    container_name: react-ui
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app/
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  #PostgreSQL Service
  db:
    image: postgres:12.0-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - vol-admisiondb:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  vol-admisiondb:
    driver: local
```
**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "awscontext",
        "Metadata": {
            "Description": "(us-east-1)",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Region": "us-east-1"
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/christopherarredondo/.docker/contexts/meta/4e8b16cafba68758d45aeeaa071ccbc6737509a9226e46364b32fd3f902f31c4",
            "TLSPath": "/Users/christopherarredondo/.docker/contexts/tls/4e8b16cafba68758d45aeeaa071ccbc6737509a9226e46364b32fd3f902f31c4"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 235
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.39-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: CSXX:K4KO:VQCJ:5CIS:LZ7K:PX64:GKY5:RJZN:G2AD:AVMD:LIJ3:CETO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine


```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by arredgroup** [comment]
In default contexts, perfectly works!! but in awscontext (ECS) I have this Issue

**Comment by kaka-ruto** [comment]
I have the same exact problem

**Comment by ndeloof** [comment]
You can't use a local path for volume binding when deploying to ECS
> `./backend:/var/www/backend`

https://github.com/docker/compose-cli/commit/06fd442a53652de2d4052bf70fda043ddacc7750#diff-1a895880a98ee19bf180b4e68854c31202cc0704c0eb19c9a0609b81395b2504R124-R132 introduce a preemptive check for this to make this more explicit

**Comment by kaka-ruto** [comment]
Removing the volumes I had did help. Thanks @ndeloof
